[package]
name = "cartilage-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "*"
winit = "*"
log = "*"
env_logger = "*"
parking_lot = "*"
pollster = "*"
bytemuck = "*"
image = "*"
glam = "*"
